// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Authenticate(arg1) {
  return window['go']['main']['App']['Authenticate'](arg1);
}

export function GetMetrics() {
  return window['go']['main']['App']['GetMetrics']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}
