// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Authenticate(arg1:string):Promise<main.AuthResponse>;

export function GetMetrics():Promise<main.MetricsData>;

export function GetStatus():Promise<string>;

export function Quit():Promise<void>;
