apiVersion: 1

datasources:
  - name: InfluxDB_Flux
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: doppio
      defaultBucket: auto-monitor
    secureJsonData:
      token: 19nU415G88QQ-k4hSad8ew0OFzcEVN6J70czpPl86Q17Qh2T5fLyxSPl3KDmcrudF3L-nkLqIh3hHIRcjfFoog==
    isDefault: true
