apiVersion: 1

datasources:
  - name: InfluxDB_Flux
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: auto-monitor-org
      defaultBucket: monitor-bucket
    secureJsonData:
      token: my-super-secret-token
    isDefault: true
