apiVersion: 1

datasources:
  - name: InfluxDB_Flux
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: doppio
      defaultBucket: auto-monitor
    secureJsonData:
      token: ZiTD13efnARy5bHqHibhF3eYim4i7CzA2XkpJ2rnNXTJuC5zScHRE4PdRjKmvpWafqbaqysJKMYkPTzzNQsMMA==
    isDefault: true
